name: generuate repo site 

on:

   push:    
   workflow_dispatch:
   pull_request:

   

    types: [opened, synchronize, edited, reopened]

    

jobs:

  generuate-repo-site:

    runs-on: ubuntu-latest

    

    steps:

      - uses: actions/checkout@v4

      - name: Setup environment

      

        uses: actions/setup-node@v4

        with:

         node-version: 18

      

      - name: Install Hexo

        run: |
          yarn global add hexo-cli

      - name: Build blog
        run: |
          yarn install
          hexo cl && hexo g

      - name: Upload blog to artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v3

        with:

          name: repo

          path: repo/public/*
